"""empty message

Revision ID: 4f9bad0487c9
Revises: None
Create Date: 2015-08-21 14:59:34.368530

"""

# revision identifiers, used by Alembic.
revision = '4f9bad0487c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
