"""empty message

Revision ID: c4ec0e0d897
Revises: None
Create Date: 2015-08-21 23:48:15.741696

"""

# revision identifiers, used by Alembic.
revision = 'c4ec0e0d897'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('raw_result_all', sa.String(), nullable=True),
    sa.Column('raw_result_no_stop_words', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    ### end Alembic commands ###
